all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: "/Users/hubert.dulay/development/aws/hubert-se.pem"

control_center: 
  hosts: 
    ec2-54-166-128-6.compute-1.amazonaws.com:

kafka_broker: 
  hosts: 
    ec2-100-26-42-241.compute-1.amazonaws.com:
    ec2-54-167-11-91.compute-1.amazonaws.com:
    ec2-54-221-144-12.compute-1.amazonaws.com:

kafka_connect: 
  hosts: 
    ec2-3-92-25-9.compute-1.amazonaws.com:

ksql: 
  hosts: 
    ec2-3-89-129-102.compute-1.amazonaws.com:

schema_registry: 
  hosts: 
    ec2-3-90-205-84.compute-1.amazonaws.com:

zookeeper: 
  hosts: 
    ec2-52-201-243-226.compute-1.amazonaws.com:
    ec2-54-145-38-50.compute-1.amazonaws.com:
    ec2-34-234-94-185.compute-1.amazonaws.com:
