all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: "/Users/hubert.dulay/development/aws/hubert-se.pem"
zookeeper:
  hosts:
    ec2-54-173-72-223.compute-1.amazonaws.com:
    ec2-35-173-187-233.compute-1.amazonaws.com:
    ec2-3-88-8-142.compute-1.amazonaws.com:
kafka_broker:
  hosts:
    ec2-54-147-76-196.compute-1.amazonaws.com:
    ec2-34-205-19-140.compute-1.amazonaws.com:
    ec2-52-23-252-107.compute-1.amazonaws.com:
schema_registry:
  hosts:
    ec2-3-91-232-76.compute-1.amazonaws.com:
control_center:
  hosts:
    ec2-34-201-37-180.compute-1.amazonaws.com:
kafka_connect:
  hosts:
    ec2-3-87-188-30.compute-1.amazonaws.com:
# kafka_rest:
#   hosts:
#     ip-172-31-34-246.us-east-2.compute.internal:
ksql:
  hosts:
    ec2-54-210-32-244.compute-1.amazonaws.com:
